package com.mkbilgisayar.tscrts.dao;

import com.mkbilgisayar.tscrts.model.TicketHistory;
import com.mkbilgisayar.tscrts.util.DatabaseUtil;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

public class TicketHistoryDAO {

    public List<TicketHistory> findByTicketId(int ticketId) {
        List<TicketHistory> historyList = new ArrayList<>();
        String sql = "SELECT * FROM ticket_history WHERE ticket_id = ? ORDER BY timestamp ASC";
        try (Connection conn = DatabaseUtil.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {
            stmt.setInt(1, ticketId);
            ResultSet rs = stmt.executeQuery();
            while (rs.next()) {
                historyList.add(mapResultSetToTicketHistory(rs));
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return historyList;
    }

    public boolean create(TicketHistory history) {
        String sql = "INSERT INTO ticket_history (ticket_id, note) VALUES (?, ?)";
        try (Connection conn = DatabaseUtil.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
            stmt.setInt(1, history.getTicketId());
            stmt.setString(2, history.getNote());
            
            int affectedRows = stmt.executeUpdate();
            if (affectedRows > 0) {
                try (ResultSet generatedKeys = stmt.getGeneratedKeys()) {
                    if (generatedKeys.next()) {
                        history.setId(generatedKeys.getInt(1));
                        // The timestamp is auto-generated by the database, 
                        // so we might want to fetch it if needed, but usually not required immediately.
                    }
                }
                return true;
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return false;
    }

    private TicketHistory mapResultSetToTicketHistory(ResultSet rs) throws SQLException {
        return new TicketHistory(
                rs.getInt("id"),
                rs.getInt("ticket_id"),
                rs.getTimestamp("timestamp"),
                rs.getString("note")
        );
    }
}
